"""Add Transaction model

Revision ID: 446d2a9c70c5
Revises: 6e864ed0cb86
Create Date: 2024-11-26 01:32:54.135185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446d2a9c70c5'
down_revision = '6e864ed0cb86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('receiver', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
