name: Test Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to test (dev, uat, prod)"
        required: true
        default: "dev"

permissions:
  contents: read

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: |
          if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
            newman run Postman/Devopps-collection.json -e Postman/dev-environment.json
          elif [ "${{ github.event.inputs.environment }}" == "uat" ]; then
            newman run Postman/Devopps-collection.json -e Postman/uat-environment.json
          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            newman run Postman/Devopps-collection.json -e Postman/prod-environment.json
          else
            echo "Invalid environment: ${{ github.event.inputs.environment }}"
            exit 1
          fi
